### ISSUE TITLE
install 6.8.1 version error

### ISSUE THREAD

**Issue by lxlxw** [lmangani/sentinl#747]
# gulp package --version=6.8.1
/usr/share/kibana/plugins/sentinl/server/lib/helpers.js:60
    return collect.concat(paths.map((path) => ({ ...route, path })));
                                                 ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/kibana/plugins/sentinl/server/lib/actions/report/install_phantomjs.js:4:59)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)

**Comment by lxlxw** [comment]
gulp package --version=6.8.1
error...
please..thx!

**Comment by JogiInnov** [comment]
+1
